[book]
title = "COGC"
authors = ["m1n9o"]
description = "Chances of Greater Consistency"
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/claywares/cogc-site"
